### ISSUE TITLE
TypeError on bme.temperature()

### ISSUE THREAD

**Issue by robmarkcole** [pimoroni/micropython-envirobit#1]
On following the instructions:
```
import bme280
bme = bme280.bme280
bme.temperature()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes 1 positional arguments but 0 were given
```

**Comment by sandyjmacdonald** [comment]
Hey Rob. Where did you find those instructions? It should be something along the lines of:

```
import bme680
sensor = bme680.BME680()
print(sensor.data.temperature)
```

**Comment by robmarkcole** [comment]
Hi @sandyjmacdonald those are the instructions from the readme. The example gives:
```python 
if __name__ == "__main__":
    b = bme280()
    while True:
        t, p, h, a = b.all()
        print("T: {t}, P: {p}, H: {h}, A: {a}".format(t=t,p=p,h=h,a=a))
        microbit.sleep(1000)
```

I've tried:
```python
>>> import bme280
>>> b = bme280.bme280()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bme280.py", line 41, in __init__
  File "bme280.py", line 30, in i2c_write
OSError: I2C write error -1010
```

Same error from:
```
b = bme280.bme280(addr=0x76)
```

**Comment by sandyjmacdonald** [comment]
Yep. I mistakenly thought for a moment that this was the BME680, then when I realised I hastily deleted my response! I’ve asked Phil if he can see what’s going on. :-)

**Comment by Gadgetoid** [comment]
The code you're using in the second attempt is correct, however the error suggests there is a hardware problem communicating with the sensor. This is the same error I get when I unplug the micro:bit from Enviro pHAT.

Is it connected firmly?

**Comment by robmarkcole** [comment]
@Gadgetoid I now gave it some real force and its gone in further and the library is working. Image below, might be an idea to include a similar shot so others know how it should sit. 
Cheers

![image](https://user-images.githubusercontent.com/11855322/43278870-2fbf474a-9104-11e8-820f-c19acd09d26a.png)
